export const TEST_IDS = {
  INPUT_TEST_ID: 'INPUT_TEST_ID',
  BUTTON_TEST_ID: 'BUTTON_TEST_ID',
  CARD_ICON_TEST_ID: 'CARD_ICON_TEST_ID',
  ERROR_MESSAGE_TEST_ID: 'ERROR_MESSAGE_TEST_ID',
  SUCCESS_MESSAGE_TEST_ID: 'SUCCESS_MESSAGE_TEST_ID',
};
